run:
  timeout: 10m
linters:
  enable-all: false
  enable:
    - errcheck
    - gofmt
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - unconvert
  disable:
    - lll
    - goconst
    - paralleltest
    - revive
