version: "2"
linters:
  enable:
    - gosec
    - misspell
    - nakedret
    - unconvert
  disable:
    - goconst
    - lll
    - paralleltest
    - revive
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - testdata$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - testdata$
