dist: goreleaser
project_name: esc
changelog:
  skip: true
release:
  disable: true
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
builds:
- id: esc
  binary: esc
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -s
  - -w
  - -X github.com/pulumi/esc/cmd/esc/cli/version.Version={{.Tag}}
  main: ./cmd/esc/
