dist: goreleaser
project_name: esc
snapshot:
  name_template: "{{ .Version }}-SNAPSHOT"
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
builds:
- id: esc
  binary: esc
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -s
  - -w
  - -X github.com/pulumi/esc/cmd/esc/internal/version.Version={{.Tag}}
  main: ./cmd/esc/
brews:
  -
    name: esc
    tap:
      owner: pulumi
      name: homebrew-tap
    commit_author:
      name: pulumi-bot
      email: bot@pulumi.com
    homepage: "https://pulumi.com"
    description: "Pulumi ESC - Manage Environments, Secrets, and Configuration"
    folder: Formula
    license: Apache-2.0
    test: |
      system "#{bin}/esc version"
