coverage:
  status:

    # Project tracks and reports the project-level coverage.
    project:
      default:
        informational: true

    # Patch tracks the coverage of the changes in a single patch.
    patch:
      default:
        informational: true

ignore:
  # None of the test data should count against coverage.
  - "**/testdata"

# Don't comment on PRs.
comment: false

# Don't post annotations to GitHub.
github_checks:
    annotations: false
