// Copyright 2026, Pulumi Corporation.
//
// Code generated by escshimgen; DO NOT EDIT.
//
// This package is a thin re-export of the ESC engine, which now lives in the
// Pulumi monorepo. Existing imports of github.com/pulumi/esc keep working.
// Deprecated: import github.com/pulumi/pulumi/sdk/v3/go/esc directly.

package esc

import canonical "github.com/pulumi/pulumi/sdk/v3/go/esc"

type (
	AccessExpr                = canonical.AccessExpr
	Accessor                  = canonical.Accessor
	BuiltinExpr               = canonical.BuiltinExpr
	EnvExecContext            = canonical.EnvExecContext
	Environment               = canonical.Environment
	EvaluatedExecutionContext = canonical.EvaluatedExecutionContext
	ExecContext               = canonical.ExecContext
	Expr                      = canonical.Expr
	Interpolation             = canonical.Interpolation
	Pos                       = canonical.Pos
	PropertyAccessor          = canonical.PropertyAccessor
	Provider                  = canonical.Provider
	Range                     = canonical.Range
	Rotator                   = canonical.Rotator
	Trace                     = canonical.Trace
	Value                     = canonical.Value
	ValueType                 = canonical.ValueType
)

// generic func (hand-shimmed in shim_generic.go): NewSecret

// generic func (hand-shimmed in shim_generic.go): NewValue

const (
	AnonymousEnvironmentName = canonical.AnonymousEnvironmentName
	AnonymousProjectName     = canonical.AnonymousProjectName
)

var (
	ErrReservedContextkey = canonical.ErrReservedContextkey
	FromJSON              = canonical.FromJSON
	NewExecContext        = canonical.NewExecContext
)
