// Copyright 2026, Pulumi Corporation.
//
// Code generated by escshimgen; DO NOT EDIT.
//
// This package is a thin re-export of the ESC engine, which now lives in the
// Pulumi monorepo. Existing imports of github.com/pulumi/esc keep working.
// Deprecated: import github.com/pulumi/pulumi/sdk/v3/go/esc/syntax/encoding directly.

package encoding

import canonical "github.com/pulumi/pulumi/sdk/v3/go/esc/syntax/encoding"

type (
	TagDecoder = canonical.TagDecoder
	YAMLSyntax = canonical.YAMLSyntax
)

var (
	DecodeValue       = canonical.DecodeValue
	DecodeYAML        = canonical.DecodeYAML
	DecodeYAMLBytes   = canonical.DecodeYAMLBytes
	EncodeValue       = canonical.EncodeValue
	EncodeYAML        = canonical.EncodeYAML
	MarshalYAML       = canonical.MarshalYAML
	UnmarshalYAML     = canonical.UnmarshalYAML
	UnmarshalYAMLNode = canonical.UnmarshalYAMLNode
)
