// Copyright 2026, Pulumi Corporation.
//
// Code generated by escshimgen; DO NOT EDIT.
//
// This package is a thin re-export of the ESC engine, which now lives in the
// Pulumi monorepo. Existing imports of github.com/pulumi/esc keep working.
// Deprecated: import github.com/pulumi/pulumi/sdk/v3/go/esc/ast directly.

package ast

import canonical "github.com/pulumi/pulumi/sdk/v3/go/esc/ast"

type (
	ArrayExpr         = canonical.ArrayExpr
	BooleanExpr       = canonical.BooleanExpr
	BuiltinExpr       = canonical.BuiltinExpr
	ConcatExpr        = canonical.ConcatExpr
	EnvironmentDecl   = canonical.EnvironmentDecl
	Expr              = canonical.Expr
	FinalExpr         = canonical.FinalExpr
	FromBase64Expr    = canonical.FromBase64Expr
	FromJSONExpr      = canonical.FromJSONExpr
	ImportDecl        = canonical.ImportDecl
	ImportListDecl    = canonical.ImportListDecl
	ImportMetaDecl    = canonical.ImportMetaDecl
	InterpolateExpr   = canonical.InterpolateExpr
	Interpolation     = canonical.Interpolation
	JoinExpr          = canonical.JoinExpr
	Node              = canonical.Node
	NullExpr          = canonical.NullExpr
	NumberExpr        = canonical.NumberExpr
	ObjectExpr        = canonical.ObjectExpr
	ObjectProperty    = canonical.ObjectProperty
	OpenExpr          = canonical.OpenExpr
	PropertyAccess    = canonical.PropertyAccess
	PropertyAccessor  = canonical.PropertyAccessor
	PropertyMapDecl   = canonical.PropertyMapDecl
	PropertyMapEntry  = canonical.PropertyMapEntry
	PropertyName      = canonical.PropertyName
	PropertySubscript = canonical.PropertySubscript
	RotateExpr        = canonical.RotateExpr
	SecretExpr        = canonical.SecretExpr
	SplitExpr         = canonical.SplitExpr
	StringExpr        = canonical.StringExpr
	SymbolExpr        = canonical.SymbolExpr
	ToBase64Expr      = canonical.ToBase64Expr
	ToJSONExpr        = canonical.ToJSONExpr
	ToStringExpr      = canonical.ToStringExpr
	ValidateExpr      = canonical.ValidateExpr
)

type ArrayDecl[T canonical.Node] = canonical.ArrayDecl[T]

type MapDecl[T canonical.Node] = canonical.MapDecl[T]

type MapEntry[T canonical.Node] = canonical.MapEntry[T]

// generic func (hand-shimmed in shim_generic.go): Number

var (
	AccessorError     = canonical.AccessorError
	Array             = canonical.Array
	ArraySyntax       = canonical.ArraySyntax
	Boolean           = canonical.Boolean
	BooleanSyntax     = canonical.BooleanSyntax
	Ciphertext        = canonical.Ciphertext
	CiphertextSyntax  = canonical.CiphertextSyntax
	Concat            = canonical.Concat
	ConcatSyntax      = canonical.ConcatSyntax
	Environment       = canonical.Environment
	EnvironmentSyntax = canonical.EnvironmentSyntax
	ExprError         = canonical.ExprError
	Final             = canonical.Final
	FinalSyntax       = canonical.FinalSyntax
	FromBase64        = canonical.FromBase64
	FromBase64Syntax  = canonical.FromBase64Syntax
	FromJSON          = canonical.FromJSON
	FromJSONSyntax    = canonical.FromJSONSyntax
	Interpolate       = canonical.Interpolate
	InterpolateSyntax = canonical.InterpolateSyntax
	Join              = canonical.Join
	JoinSyntax        = canonical.JoinSyntax
	MustInterpolate   = canonical.MustInterpolate
	Null              = canonical.Null
	NullSyntax        = canonical.NullSyntax
	NumberSyntax      = canonical.NumberSyntax
	Object            = canonical.Object
	ObjectSyntax      = canonical.ObjectSyntax
	Open              = canonical.Open
	OpenSyntax        = canonical.OpenSyntax
	ParseEnvironment  = canonical.ParseEnvironment
	ParseExpr         = canonical.ParseExpr
	Plaintext         = canonical.Plaintext
	PlaintextSyntax   = canonical.PlaintextSyntax
	Rotate            = canonical.Rotate
	RotateSyntax      = canonical.RotateSyntax
	Split             = canonical.Split
	SplitSyntax       = canonical.SplitSyntax
	String            = canonical.String
	StringSyntax      = canonical.StringSyntax
	StringSyntaxValue = canonical.StringSyntaxValue
	Symbol            = canonical.Symbol
	ToBase64Syntax    = canonical.ToBase64Syntax
	ToJSON            = canonical.ToJSON
	ToJSONSyntax      = canonical.ToJSONSyntax
	ToString          = canonical.ToString
	ToStringSyntax    = canonical.ToStringSyntax
	Validate          = canonical.Validate
	ValidateSyntax    = canonical.ValidateSyntax
)
