// Copyright 2026, Pulumi Corporation.
//
// Code generated by escshimgen; DO NOT EDIT.
//
// This package is a thin re-export of the ESC engine, which now lives in the
// Pulumi monorepo. Existing imports of github.com/pulumi/esc keep working.
// Deprecated: import github.com/pulumi/pulumi/sdk/v3/go/esc/syntax directly.

package syntax

import canonical "github.com/pulumi/pulumi/sdk/v3/go/esc/syntax"

type (
	ArrayNode         = canonical.ArrayNode
	BooleanNode       = canonical.BooleanNode
	Diagnostic        = canonical.Diagnostic
	Diagnostics       = canonical.Diagnostics
	Node              = canonical.Node
	NullNode          = canonical.NullNode
	NumberNode        = canonical.NumberNode
	NumberValue       = canonical.NumberValue
	ObjectNode        = canonical.ObjectNode
	ObjectPropertyDef = canonical.ObjectPropertyDef
	Scalar            = canonical.Scalar
	StringNode        = canonical.StringNode
	Syntax            = canonical.Syntax
	Trivia            = canonical.Trivia
)

// generic func (hand-shimmed in shim_generic.go): AsNumber

// generic func (hand-shimmed in shim_generic.go): Number

// generic func (hand-shimmed in shim_generic.go): NumberSyntax

var (
	Array                = canonical.Array
	ArraySyntax          = canonical.ArraySyntax
	Boolean              = canonical.Boolean
	BooleanSyntax        = canonical.BooleanSyntax
	CopyTrivia           = canonical.CopyTrivia
	Error                = canonical.Error
	NoSyntax             = canonical.NoSyntax
	NodeError            = canonical.NodeError
	Null                 = canonical.Null
	NullSyntax           = canonical.NullSyntax
	Object               = canonical.Object
	ObjectProperty       = canonical.ObjectProperty
	ObjectPropertySyntax = canonical.ObjectPropertySyntax
	ObjectSyntax         = canonical.ObjectSyntax
	String               = canonical.String
	StringSyntax         = canonical.StringSyntax
	Walk                 = canonical.Walk
)
