// Copyright 2026, Pulumi Corporation.
//
// Code generated by escshimgen; DO NOT EDIT.
//
// This package is a thin re-export of the ESC engine, which now lives in the
// Pulumi monorepo. Existing imports of github.com/pulumi/esc keep working.
// Deprecated: import github.com/pulumi/pulumi/sdk/v3/go/esc/schema directly.

package schema

import canonical "github.com/pulumi/pulumi/sdk/v3/go/esc/schema"

type (
	ArrayBuilder   = canonical.ArrayBuilder
	BooleanBuilder = canonical.BooleanBuilder
	Builder        = canonical.Builder
	BuilderMap     = canonical.BuilderMap
	MapBuilder     = canonical.MapBuilder
	NullBuilder    = canonical.NullBuilder
	NumberBuilder  = canonical.NumberBuilder
	ObjectBuilder  = canonical.ObjectBuilder
	Schema         = canonical.Schema
	SchemaMap      = canonical.SchemaMap
	StringBuilder  = canonical.StringBuilder
)

var (
	Always           = canonical.Always
	AnyOf            = canonical.AnyOf
	Array            = canonical.Array
	Boolean          = canonical.Boolean
	JSONSchemaSchema = canonical.JSONSchemaSchema
	Never            = canonical.Never
	Null             = canonical.Null
	Number           = canonical.Number
	Object           = canonical.Object
	OneOf            = canonical.OneOf
	Record           = canonical.Record
	Ref              = canonical.Ref
	String           = canonical.String
	Tuple            = canonical.Tuple
)
