// Copyright 2026, Pulumi Corporation.
//
// Code generated by escshimgen; DO NOT EDIT.
//
// This package is a thin re-export of the ESC engine, which now lives in the
// Pulumi monorepo. Existing imports of github.com/pulumi/esc keep working.
// Deprecated: import github.com/pulumi/pulumi/sdk/v3/go/esc/analysis directly.

package analysis

import canonical "github.com/pulumi/pulumi/sdk/v3/go/esc/analysis"

type (
	Analysis = canonical.Analysis
)

var (
	New = canonical.New
)
