name: Run Acceptance Tests from PR

on:
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CHANGELOG_PENDING.md'

jobs:
  lint:
    uses: ./.github/workflows/stage-lint.yml
  test:
    uses: ./.github/workflows/stage-test.yml
    with:
      enable-coverage: true
    secrets: inherit
